# Generated by Django 6.0.1 on 2026-02-03 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_reportjob"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedreport",
            name="is_processed",
            field=models.BooleanField(default=False),
        ),
    ]
