# Generated by Django 6.0.1 on 2026-02-03 08:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_generatedreport_is_processed'),
    ]

    operations = [
        migrations.CreateModel(
            name='URLScanIOResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('scan_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('response', models.JSONField(blank=True, null=True)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='screenshots/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
