# Generated by Django 6.0.1 on 2026-02-05 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_geminiresponse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generatedreport',
            old_name='response',
            new_name='openai_response',
        ),
        migrations.RenameField(
            model_name='scannedurl',
            old_name='response',
            new_name='openai_response',
        ),
        migrations.AddField(
            model_name='generatedreport',
            name='gemini_response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.geminiresponse'),
        ),
        migrations.AddField(
            model_name='generatedreport',
            name='model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scannedurl',
            name='gemini_response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.geminiresponse'),
        ),
        migrations.AddField(
            model_name='scannedurl',
            name='model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
