# Generated by Django 6.0.1 on 2026-02-05 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_response_generatedreport_openai_response_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('ai_threat_score', models.IntegerField(blank=True, null=True)),
                ('ai_threat_label', models.CharField(blank=True, max_length=32, null=True)),
                ('actual_threat', models.CharField(choices=[('safe', '안전'), ('warn', '주의'), ('risk', '위험')], max_length=16)),
                ('details', models.TextField(blank=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
