# Generated by Django 6.0.1 on 2026-02-05 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_inquire'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedreport',
            name='is_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inquire',
            name='accept_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inquire',
            name='is_accept',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scannedurl',
            name='is_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='GeneratedReportEditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('threat_type', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('probability', models.IntegerField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('edited_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_logs', to='api.generatedreport')),
            ],
        ),
        migrations.CreateModel(
            name='ScannedURLEditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('threat_type', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('threat_score', models.IntegerField(blank=True, null=True)),
                ('edited_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scanned_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_logs', to='api.scannedurl')),
            ],
        ),
    ]
